---
- name: Install virtualenv and virtualenvwrapper
  pacman: name=python-virtualenvwrapper state=present

- name: Create system environment group
  group: name=env state=present

- name: Add user to system environment group
  user: name={{ user.name }} groups=env append=yes

- name: Create system environment dir
  file: path=/usr/local/env state=directory group=env mode=0775
