---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: cron, tags: ['cron'] }
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    - { role: grsec, tags: ['grsec'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: x, tags: ['x'] }
    - { role: slim, tags: ['slim'] }
    - { role: i3, tags: ['i3'] }
    - { role: iptables, tags: ['iptables'] }
    - { role: nettools, tags: ['nettools'] }
    - { role: networkmanager, tags: ['networkmanager'] }
    - { role: macchiato, tags: ['macchiato'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: firejail, tags: ['firejail'] }
    - { role: unbound, tags: ['unbound'] }
    - { role: editors, tags: ['editors'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: archive, tags: ['archive'] }
    - { role: udisks, tags: ['udisks'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: yubikey, tags: ['yubikey'] }
    - { role: media, tags: ['media'] }
    - { role: mpd, tags: ['mpd'] }
    - { role: mpv, tags: ['mpv'] }
    - { role: pianobar, tags: ['pianobar'] }
    - { role: laptop, tags: ['laptop'] }
    - { role: thinkpad, tags: ['thinkpad'], when: "'ThinkPad' in ansible_product_version" }
    - { role: macbook, tags: ['macbook'], when: "'MacBook' in ansible_product_name" }
    - { role: screensaver, tags: ['screensaver'] }
    - { role: bitlbee, tags: ['bitlbee'] }
    - { role: weechat, tags: ['weechat'] }
    - { role: git-annex, tags: ['git-annex'] }
    - { role: ledger, tags: ['ledger'] }
    - { role: mail, tags: ['mail'] }
    - { role: cups, tags: ['cups'] }
    - { role: office, tags: ['office'] }
    - { role: redshift, tags: ['redshift'] }
    - { role: rtorrent, tags: ['rtorrent'] }
    - { role: virtualbox, tags: ['virtualbox'] }
    - { role: hashicorp, tags: ['hashicorp'] }
    - { role: virtualenv, tags: ['virtualenv'] }
    - { role: backup, tags: ['backup'] }
    - { role: tarsnap, tags: ['tarsnap'] }
    - { role: mapping, tags: ['mapping'] }
    - { role: sound, tags: ['sound'] }
    - { role: pim, tags: ['pim'] }
    - { role: radio, tags: ['radio'] }
    - { role: formd, tags: ['formd'] }
    - { role: postgresql, tags: ['postgresql'] }
    - { role: calibre, tags: ['calibre'] }
    - { role: cli53, tags: ['cli53'] }
    - { role: tor, tags: ['tor'] }
    - { role: parcimonie, tags: ['parcimonie'] }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
