---
- name: Install signal-desktop
  pacman:
    name: signal-desktop
    state: present

- name: Jail signal-desktop
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/signal-desktop
    state: link
  tags:
    - firejail
