---
- name: Install Tarsnap
  pacman: name=tarsnap state=present

- name: Copy default Tarsnap config
  copy: src=/etc/tarsnap/tarsnap.conf.sample dest=/etc/tarsnap/tarsnap.conf

- name: Create Tarsnap cache dir
  file: path=/usr/local/tarsnap-cache state=directory

- name: Humanize Tarsnap numbers
  lineinfile: dest=/etc/tarsnap/tarsnap.conf
              state=present
              line=humanize-numbers

- name: Install Tarsnapper into virtual environment
  pip: name=tarsnapper
       virtualenv=/usr/local/env/tarsnapper
       virtualenv_command=virtualenv2

- name: Link Tarsnapper to bin
  file: src=/usr/local/env/tarsnapper/bin/tarsnapper
        dest=/usr/local/bin/tarsnapper
        state=link

- name: Create Tarsnapper config include dir
  file: path=/usr/local/etc/tarsnapper.d/ state=directory

- name: Push Tarsnapper config
  template: src=tarsnapper.conf.j2 dest=/usr/local/etc/tarsnapper.conf

- name: Push Tarsnapper service file
  copy: src=tarsnapper.service dest=/etc/systemd/system/tarsnapper.service
  notify:
    - reload systemd config

- name: Push Tarsnapper timer file
  template: src=tarsnapper.timer.j2 dest=/etc/systemd/system/tarsnapper.timer
  notify:
    - reload systemd config
    - restart tarsnapper

- name: Enable and start Tarsnapper timer
  service: name=tarsnapper.timer enabled=yes state=started
  when: tarsnapper.timer.run_on == "all"

- name: Remove Tarsnapper from trusted unit list
  lineinfile: dest=/usr/local/etc/trusted_units
              state=absent
              line=tarsnapper.timer
  when: tarsnapper.timer.run_on == "all"

- name: Disable Tarsnapper timer
  service: name=tarsnapper.timer enabled=no
  when: tarsnapper.timer.run_on == "trusted"

- name: Add Tarsnapper to trusted unit list
  lineinfile: dest=/usr/local/etc/trusted_units
              state=present
              line=tarsnapper.timer
  when: tarsnapper.timer.run_on == "trusted"
