---
- name: Install w3m
  pacman: name=w3m state=present

- name: Install Firefox
  pacman: name=firefox state=present
  tags:
    - firefox

- name: Jail Firefox
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/firefox
        state=link
  tags:
    - firefox
    - firejail

- name: Push Firefox firejail profile
  copy: src=firejail/firefox.profile dest=/usr/local/etc/firejail/firefox.profile
  notify:
    - activate firejail profiles
  tags:
    - firefox
    - firejail

- name: Install Chromium
  pacman: name=chromium state=present
  tags:
    - chromium

- name: Jail Chromium
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/chromium
        state=link
  tags:
    - chromium
    - firejail

- name: Push Chromium firejail profile
  copy: src=firejail/chromium.profile dest=/usr/local/etc/firejail/chromium.profile
  notify:
    - activate firejail profiles
  tags:
    - chromium
    - firejail

- name: Install Pepper Flash
  aur: name=pepper-flash user={{ user.name }}
  tags:
    - aur
    - chromium

- name: Install tor-browser-en
  aur: name=tor-browser-en user={{ user.name }} skip_pgp=yes
  tags:
    - tor-browser
    - aur

- name: Jail tor-browser-en
  copy: src=tor-browser-en.sh dest=/usr/local/bin/tor-browser-en mode=0755
  tags:
    - tor-browser
    - firejail
    - grsec

- name: Push rofi browser chooser
  template: src=browser.sh.j2 dest=/usr/local/bin/browser mode=0755
  tags:
    - rofi
    - chooser

- name: Create local desktop application dir
  file: path=/usr/local/share/applications state=directory
  tags:
    - rofi
    - chooser

- name: Push rofi browser chooser desktop file
  copy: src=browser.desktop dest=/usr/local/share/applications/browser.desktop
  tags:
    - rofi
    - chooser

- name: Verify mimeapps.list exists
  file: path=/etc/xdg/mimeapps.list state=touch
  tags:
    - rofi
    - chooser

- name: Set rofi browser chooser as default application for relevant mimetypes
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^text/html=', line: 'text/html=browser.desktop' }
    - { regexp: '^text/xml=', line: 'text/xml=browser.desktop' }
    - { regexp: '^text/mml=', line: 'text/mml=browser.desktop' }
    - { regexp: '^application/xhtml\+xml=', line: 'application/xhtml+xml=browser.desktop' }
    - { regexp: '^application/xml=', line: 'application/xml=browser.desktop' }
    - { regexp: '^x-scheme-handler/http=', line: 'x-scheme-handler/http=browser.desktop' }
    - { regexp: '^x-scheme-handler/https=', line: 'x-scheme-handler/https=browser.desktop' }
  tags:
    - rofi
    - chooser

- name: Install surfraw
  pacman: name=surfraw state=present
  tags:
    - surfraw

- name: Configure surfraw browser
  lineinfile:
    dest: /etc/xdg/surfraw/conf
    regexp: '^def   SURFRAW_graphical_browser	'
    line: 'def   SURFRAW_graphical_browser	/usr/local/bin/browser'
  tags:
    - surfraw
    - chooser

- name: Push surfraw-rofi script
  copy: src=surfraw-rofi dest=/usr/local/bin/surfraw-rofi mode=0755
  tags:
    - surfraw
    - rofi
