---
- name: Install GNU Units
  kewlfft.aur.aur:
    name: units
    use: makepkg
    skip_pgp_check: yes
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur

- include_tasks: roles/nmtrust/tasks/unit.yml
  vars:
      unit: units_currency.timer
      run_on: "{{ units.run_on }}"
