---
- name: Install sudo
  pacman: name=sudo state=present

- name: Add user to wheel group
  user: name={{ user.name }} groups=wheel append=yes
  tags:
    - user

- name: Copy sudo wheel group configuration
  template: src=sudo_wheel.j2 dest=/etc/sudoers.d/01_wheel mode=440 validate='visudo -cf %s'
