---
- name: Push mail sync script
  template: src=mailsync.sh.j2 dest=/usr/local/bin/mailsync mode=755
  tags:
    - mailsync

- name: Push mailsync service file
  template: src=mailsync.service.j2 dest=/etc/systemd/user/mailsync.service
  tags:
    - mailsync
  notify:
    - reload systemd config

- name: Push mailsync timer file
  template: src=mailsync.timer.j2 dest=/etc/systemd/user/mailsync.timer
  tags:
    - mailsync
  notify:
    - reload systemd config
    - restart mailsync

- name: Enable and start mailsync timer
  systemd: name=mailsync.timer user=yes enabled=yes state=started
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  when: mail.sync_on == "all"
  tags:
    - mailsync

- name: Remove mailsync from trusted unit list
  lineinfile: dest=/etc/nmtrust/trusted_units
              state=absent
              line="mailsync.timer,user:{{ user.name }}"
  when: mail.sync_on == "all"
  tags:
    - mailsync

- name: Disable mailsync timer
  systemd: name=mailsync.timer user=yes enabled=no
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  when: mail.sync_on == "trusted"
  tags:
    - mailsync

- name: Add mailsync to trusted unit list
  lineinfile: dest=/etc/nmtrust/trusted_units
              state=present
              line="mailsync.timer,user:{{ user.name }}"
  when: mail.sync_on == "trusted"
  tags:
    - mailsync
