---
- name: Install himawaripy into virtual environment
  pip: name=git+https://github.com/boramalper/himawaripy#egg=himawaripy
       virtualenv=/usr/local/env/himawaripy
       virtualenv_command=virtualenv3

- name: Link himawaripy to bin
  file: src=/usr/local/env/himawaripy/bin/himawaripy
        dest=/usr/local/bin/himawaripy
        state=link

- name: Push himawaripy service file
  template: src=himawaripy.service.j2 dest=/etc/systemd/user/himawaripy.service
  notify:
    - reload systemd config

- name: Push himawaripy timer file
  template: src=himawaripy.timer.j2 dest=/etc/systemd/user/himawaripy.timer
  notify:
    - reload systemd config
    - restart himawaripy

- name: Enable and start himawaripy timer
  systemd: name=himawaripy.timer user=yes enabled=yes state=started
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  when: himawaripy.run_on == "all"

- name: Remove himawaripy from trusted unit list
  lineinfile: dest=/etc/nmtrust/trusted_units
              state=absent
              line="himawaripy.timer,user:{{ user.name }}"
  when: himawaripy.run_on == "all"

- name: Disable himawaripy timer
  systemd: name=himawaripy.timer user=yes enabled=no
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  when: himawaripy.run_on == "trusted"

- name: Add himawaripy to trusted unit list
  lineinfile: dest=/etc/nmtrust/trusted_units
              state=present
              line="himawaripy.timer,user:{{ user.name }}"
  when: himawaripy.run_on == "trusted"
