---
- include: beets.yml
- include: abcde.yml
- include: imagemagick.yml
- include: inkscape.yml
- include: gimp.yml
- include: gthumb.yml
- include: feh.yml
- include: imv.yml
- include: mcomix.yml
- include: teiler.yml
- include: flac2all.yml
- include: darktable.yml
- include: qcode.yml

- name: Install misc media codecs and helpers
  pacman:
    name:
      - flac
      - lame
      - gst-libav
      - gst-plugins-good
      - exiv2
      - perl-image-exiftool
      - perl-archive-zip
      - opus-tools
    state: present

- name: Install Metadata Anonymisation Toolkit
  pacman:
    name: mat2
    state: present
  tags:
    - mat

- name: Install youtube-dl
  pacman:
    name: youtube-dl
    state: present

- name: Install zbar
  pacman:
    name: zbar
    state: present

- name: Install sxiv
  pacman:
    name: sxiv
    state: present

- name: Install svgcleaner
  pacman:
    name: svgcleaner
    state: present

- name: Install flameshot
  pacman:
    name: flameshot
    state: present

- name: Install digikam
  pacman:
    name: digikam
    state: present
