---
- include: beets.yml
- include: abcde.yml
- include: xfburn.yml
- include: imagemagick.yml
- include: inkscape.yml
- include: gimp.yml
- include: gthumb.yml
- include: feh.yml
- include: imv.yml
- include: mcomix.yml
- include: teiler.yml
- include: flac2all.yml
- include: darktable.yml
- include: qcode.yml

- name: Install misc media codecs and helpers
  pacman: name={{ item }} state=present
  with_items:
    - flac
    - lame
    - gst-libav
    - gst-plugins-good
    - exiv2
    - perl-image-exiftool
    - opus-tools

- name: Install Metadata Anonymisation Toolkit and dependencies
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - hachoir-core
    - hachoir-parser
    - mat
  tags:
    - aur

- name: Install youtube-dl
  pacman: name=youtube-dl state=present
