---
- name: Install fldigi
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - cty
    - fldigi
  tags:
    - aur

- name: Install wsjtx
  aur: name=wsjtx user={{ user.name }}
  tags:
    - aur

# tucnak3 replaced by tucnak4 upstream but no AUR package yet
#- name: Install tucnak3
#  aur: name={{ item }} user={{ user.name }}
#  with_items:
#    - libzia3
#    - tucnak3
#  tags:
#    - aur
