---
- name: Install alsa-utils
  pacman: name=alsa-utils state=present

- name: Install PulseAudio
  pacman: name={{ item }} state=present
  with_items:
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol

- name: Switch output to newly connected devices
  lineinfile: dest=/etc/pulse/default.pa
              state=present
              line="load-module module-switch-on-connect"

- name: Install pasystray
  aur: name=pasystray-gtk3-standalone user={{ user.name }}
  tags:
    - aur

- name: Install pulseaudio-ctl
  aur: name=pulseaudio-ctl user={{ user.name }}
  tags:
    - aur
